//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateTableFromDatabase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.RoomSubject = new HashSet<RoomSubject>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> Students { get; set; }
        public Nullable<int> Lunch { get; set; }
        public Nullable<int> BreakMon { get; set; }
        public Nullable<int> BreakTue { get; set; }
        public Nullable<int> BreakWed { get; set; }
        public Nullable<int> BreakThu { get; set; }
        public Nullable<int> BreakFri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomSubject> RoomSubject { get; set; }
    }
}
