//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateTableFromDatabase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public int id { get; set; }
        public string deviceID { get; set; }
        public Nullable<double> dust { get; set; }
        public Nullable<double> ldr { get; set; }
        public Nullable<double> humidity { get; set; }
        public Nullable<double> co2 { get; set; }
        public Nullable<double> temp { get; set; }
        public string timesent { get; set; }
        public Nullable<double> noise { get; set; }
        public Nullable<double> noisemin { get; set; }
        public Nullable<double> noisemax { get; set; }
        public int fk_DeviceID { get; set; }
    }
}
